all: clean

clean: 
	find . -name "*.class" -exec rm -rf {} \;


run-decorator:
	javac decorator/*.java
	java  decorator.iPhoneTest

run-interpreter:
	javac interpreter/*.java
	java  interpreter.ParserTest


