
clean:
	rm -f *.png *.svg

install:
	open https://github.com/wandernauta/yuml
	sudo pip install https://github.com/wandernauta/yuml/zipball/master

test:
	yuml -i test.yuml -o test.png -f png -t class -s scruffy 

test1:
	yuml -i test1.yuml -o test1.png -f png -t class -s scruffy 

test2:
	yuml -i test2.yuml -o test2.png -f png -t class -s scruffy 

test3:
	yuml -i test3.yuml -o test3.png -f png -t class -s scruffy 

test4:
	yuml -i test4.yuml -o test4.png -f png -t class -s scruffy 

test5:
	yuml -i test5yuml -o test5.png -f png -t class -s scruffy 




	 
