
clean:
	rm -f *.png *.svg

install:
	open https://www.spinellis.gr/umlgraph/
	open https://www.spinellis.gr/umlgraph/doc/indexw.html
	open https://www.imagemagick.org/script/download.php
	open https://www.graphviz.org/
	open https://brewformulas.org/Imagemagick
	brew install plotutils
	brew install graphviz
	brew install imagemagick

umlgraph1:
	umlgraph umlgraph1 png
	
umlgraph2:
	umlgraph umlgraph2 png
	
umlgraph3:
	umlgraph umlgraph3 png
	
umlgraph4:
	umlgraph umlgraph4 png
	
umlgraph5:
	umlgraph umlgraph5 png
	
umlgraph6:
	umlgraph umlgraph6 png
	
umlgraph7:
	 pic2plot -T svg umlgraph7.pic > umlgraph7.svg
	 convert umlgraph7.svg umlgraph7.png

umlgraph8:
	 pic2plot -T svg umlgraph8.pic > umlgraph8.svg
	 convert umlgraph8.svg umlgraph8.png	

umlgraph9:
	 pic2plot -T svg umlgraph9.pic > umlgraph9.svg
	 convert umlgraph9.svg umlgraph9.png
	 
umlgraph10:
	 pic2plot -T svg umlgraph10.pic > umlgraph10.svg
	 convert umlgraph10.svg umlgraph10.png
	 
umlgraph11:
	 pic2plot -T svg umlgraph11.pic > umlgraph11.svg
	 convert umlgraph11.svg umlgraph11.png
	 
umlgraph12:
	 pic2plot -T svg umlgraph12.pic > umlgraph12.svg
	 convert umlgraph12.svg umlgraph12.png

umlgraph7-on-mac:
	 pic2plot -T svg umlgraph7.pic > umlgraph7.svg
	 qlmanage -t -s 1000 -o . umlgraph7.svg
	 mv umlgraph7.svg.png umlgraph7.png 

umlgraph8-on-mac:
	 pic2plot -T svg umlgraph8.pic > umlgraph8.svg
	 qlmanage -t -s 1000 -o . umlgraph8.svg
	 mv umlgraph8.svg.png umlgraph8.png 	

umlgraph9-on-mac:
	 pic2plot -T svg umlgraph9.pic > umlgraph9.svg
	 qlmanage -t -s 1000 -o . umlgraph9.svg
	 mv umlgraph9.svg.png umlgraph9.png 
	 
umlgraph10-on-mac:
	 pic2plot -T svg umlgraph10.pic > umlgraph10.svg
	 qlmanage -t -s 1000 -o . umlgraph10.svg
	 mv umlgraph10.svg.png umlgraph10.png 
	 
umlgraph11-on-mac:
	 pic2plot -T svg umlgraph11.pic > umlgraph11.svg
	 qlmanage -t -s 1000 -o . umlgraph11.svg
	 mv umlgraph11.svg.png umlgraph11.png 
	 
umlgraph12-on-mac:
	 pic2plot -T svg umlgraph12.pic > umlgraph12.svg
	 qlmanage -t -s 1000 -o . umlgraph12.svg
	 mv umlgraph12.svg.png umlgraph12.png 

	 
