all: clean

clean: 
	find . -name "*.class" -exec rm -rf {} \;

compile:
	javac *.java

run: compile
	java -cp . GumballMachine
	
run1: compile
	java -cp . GumballMachine1
	
run2: compile
	java -cp . GumballMachine2

run3: compile
	java -cp . GumballMachine3
	
